In [1]:
'''
MacOS专用字体设置
MacOS 系统中使用的中文字体路径
适用于MacOS15版本
可直接复制到代码中使用
'''
import matplotlib.pyplot as plt
from matplotlib import font_manager
# 设置字体路径
font_path = '/System/Library/Fonts/STHeiti Medium.ttc'

# 加载字体
my_font = font_manager.FontProperties(fname=font_path)

# 设置为默认字体
plt.rcParams['font.family'] = my_font.get_name()
plt.rcParams['axes.unicode_minus'] = False  # 正确显示负号

In [2]:
import pandas as pd
df = pd.read_excel('新闻.xlsx')
df.head()

关键词                            标题  \
0  华能信托            信托公司2019年上半年经营业绩概览   
1  华能信托                  首单信托型企业ABS获批   
2  华能信托       华能贵诚信托孙磊:金融科技助力打造开放信托生态   
3  华能信托  华能贵诚信托孙磊:金融科技已经成为信托行业重要的基础设施   
4  华能信托      格力电器股权转让意向方闭门开会 华能信托赫然在列   

                                                  网址       来源  \
0  http://www.financialnews.com.cn/jrsb_m/xt/zx/2...  中国金融新闻网   
1     http://www.jjckb.cn/2018-10/23/c_137552198.htm    经济参考网   
2  https://baijiahao.baidu.com/s?id=1639276579449...    同花顺财经   
3       https://finance.qq.com/a/20190716/007898.htm     腾讯财经   
4  https://finance.sina.com.cn/trust/roll/2019-05...       新浪   

                  时间  
0  2019年07月23日 00:00  
1  2018年10月23日 12:21  
2  2019年07月17日 10:49  
3  2019年07月16日 18:53  
4  2019年05月22日 22:53

In [3]:
import jieba
words = []
for i, row in df.iterrows():
    words.append(' '.join(jieba.cut(row['标题'])))

Building prefix dict from the default dictionary ...
Loading model from cache /var/folders/yt/dl86x1493y18124bcx2hmh780000gn/T/jieba.cache
Loading model cost 0.401 seconds.
Prefix dict has been built successfully.


In [4]:
words[0:3]

['信托公司 2019 年 上半年 经营 业绩 概览',
 '首单 信托 型 企业 ABS 获批',
 '华能 贵 诚信 托孙磊 : 金融 科技 助力 打造 开放 信托 生态']

# 词袋法

In [5]:
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer()
X = vect.fit_transform(words)
X = X.toarray()

# TF-IDF

In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer

vect = TfidfVectorizer()
X = vect.fit_transform(words)
X = X.toarray()

In [7]:
print(X)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [8]:
words_bag = vect.vocabulary_
print(words_bag)

{'信托公司': 630, '2019': 21, '上半年': 296, '经营': 2659, '业绩': 345, '概览': 2130, '首单': 3337, '信托': 628, '企业': 538, 'abs': 103, '获批': 2827, '华能': 896, '诚信': 2947, '托孙磊': 1721, '金融': 3199, '科技': 2541, '助力': 854, '打造': 1720, '开放': 1553, '生态': 2408, '已经': 1467, '成为': 1673, '行业': 2860, '重要': 3191, '基础设施': 1135, '格力电器': 2116, '股权': 2754, '转让': 3063, '意向': 1664, '闭门': 3229, '开会': 1535, '赫然': 3013, '直击': 2465, '投资者': 1744, '见面会': 2886, '参会者': 934, '背后': 2758, '国务院': 1091, '国资委': 1098, '召开': 972, '自称': 2784, '人士': 492, '到场': 818, '2018': 20, '信托业': 629, '人均': 491, '创利': 798, '304': 44, '万元': 273, '华润': 895, '贵诚': 2992, '跌出': 3039, '万亿': 272, '俱乐部': 633, '去年': 932, '托跌出': 1724, '200': 17, '收购': 1854, '50': 60, '亿爆雷': 508, '烫手山芋': 2323, '如何': 1269, '处置': 1152, '外界': 1159, '传言': 564, '泰禾': 2221, '引进': 1566, '战投': 1695, '目标': 2464, '之一': 407, '行业动态': 2861, '山东': 1438, '年报': 1497, '规模': 2890, '缩水': 2686, '曲线': 2021, '上市': 297, '浪潮': 2241, '再度': 739, '托换帅': 1722, '孙磊': 1303, '出任': 764, '总经理': 1641, '换帅': 179

In [9]:
len(words_bag)

3402

In [10]:
# 将之前所有的新闻标题进行文本向量化并通过pandas展示
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

# 文本向量化
vect = CountVectorizer()
X = vect.fit_transform(words)  # 将分词后的内容文本向量化
X = X.toarray()

# 查看文本向量化的结果
words_bag2 = vect.get_feature_names_out()
df = pd.DataFrame(X, columns=words_bag2)
df.head()

00700  03  04  08s  09  10  100  11  12  150  ...  黄萍  黄金  黑客  黑灰产  黑金  黑马  \
0      0   0   0    0   0   0    0   0   0    0  ...   0   0   0    0   0   0   
1      0   0   0    0   0   0    0   0   0    0  ...   0   0   0    0   0   0   
2      0   0   0    0   0   0    0   0   0    0  ...   0   0   0    0   0   0   
3      0   0   0    0   0   0    0   0   0    0  ...   0   0   0    0   0   0   
4      0   0   0    0   0   0    0   0   0    0  ...   0   0   0    0   0   0   

   鼓手  鼻祖  齐聚  龙风  
0   0   0   0   0  
1   0   0   0   0  
2   0   0   0   0  
3   0   0   0   0  
4   0   0   0   0  

[5 rows x 3402 columns]

In [11]:
from sklearn.cluster import KMeans
kms = KMeans(n_clusters=10, random_state=123)
k_data = kms.fit_predict(df)

/opt/anaconda3/lib/python3.12/site-packages/sklearn/cluster/_kmeans.py:1416: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)


In [12]:
print(k_data)

[5 5 4 4 5 5 5 5 5 9 5 9 9 5 5 5 5 9 5 5 9 5 9 5 5 5 5 5 5 5 9 5 9 8 9 5 5
 6 9 9 5 9 8 9 5 5 6 9 9 5 9 8 9 5 5 6 9 9 5 9 8 9 5 5 6 9 9 5 9 8 9 5 5 6
 9 9 5 9 8 9 5 5 6 9 9 5 9 8 9 5 5 6 9 1 1 1 1 5 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 5 1 1 1 1 5 1 5 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 5 1 1 1 1 5 5 5 5 5 5 5 5 5 5 3 5 5 5 5 5 5 5 5 5 5 3 5 4 5 5 4 3 5
 5 5 5 5 5 5 5 5 3 4 3 5 5 3 5 4 5 5 5 5 5 4 5 4 5 4 4 3 5 5 5 5 5 5 5 5 5
 4 5 5 5 5 5 5 5 5 5 5 5 5 5 5 3 5 5 5 5 5 5 5 5 4 3 5 5 4 5 4 5 5 4 5 5 5
 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 5 0 5 0 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 7 7 7 7 7 7 7 5 7 7 7 7 7 7
 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7
 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 5 5 5 

In [13]:
import numpy as np
words_ary = np.array(words)
print(words_ary[k_data == 1])  # 可以把数字1改成其他数字看看效果

['杨广伟 : 未来 10 年   人工智能 一定 会 改变 房地产 行业' '文献 述评 : 人工智能 在 精神科 的 应用'
 '严重 提醒 ! 骗子 都 用 上 AI 技术 了 ! 你 却 还 不 知道 啥 是 人工智能 ?'
 '“ 芯 时代 、 芯 征程 、 芯 机遇 ” 人工智能 与 机器 视觉 高峰论坛 如期而至'
 '“ 读心术 ” 新高 地 , 基于 血谱 光学 成像 的 情感 人工智能'
 '生态 伙伴 招募 , 京东 AI “ 炼金 计划 ” 开启 人工智能 共生 时代'
 '人工智能 融合 商业化 场景 发展 , 实践 落地 需 注重 三大 核心' '渗透 ! 人工智能 将 在 10 年内 占领 房地产 市场 ?'
 '言通 专注 人工智能 领域 的 语音 识别 服务 , 多维度 赋能 智能 营销'
 '阿尔法 蛋 现身 人工智能 与 教育 大 数据 峰会 , 智能 科技 获点 赞'
 '世界 人工智能 大会 看点 | 聚焦 全球 人工智能 健康 峰会 : 智汇 健康   预见 未来'
 '亚马逊 的 StyleSnap 是 一款 人工智能 工具'
 '倒计时 22 天 ! 众多 民生 类 展商 将 亮相 2019 世界 人工智能 大会'
 '... 联想 宣布 开展 为期 多年 的 全球 合作 , 提升 在 高性能 计算 和 人工智能 ...'
 '百度 副总裁 张旭 阳   人工智能 时代 下 的 金融 新 生态' '学好 少儿 编程 , 未来 轻松 掌控 人工智能 时代'
 '人工智能 是 跨境 电商 新 的 机遇 吗 ?' '人工智能 将 如何 改变 交通运输 行业'
 '西媒 盘点 : 2016 年 中国 打响 了 人工智能 发展 的 发令枪'
 '人工智能 技术 背后 的 碳 足迹 惊人 , 研究 人员 呼吁 提高 创新 效率'
 '乐队 鼓手 要 失业 ? 索尼 用 人工智能 自动 为 音乐 打 节拍' '盘点 全球 各国 人工智能 战略 : 中国 打响 发令枪'
 '构筑 我国 人工智能 新 优势' '赛事 对标 国际   人工智能 高手 齐聚 鹭岛 竞技'
 '国家 新一代 人工智能 开放 创新 平台   2019 年 人工智能 市场 规模 将近 280 ...'
 '既 要 人工智能 高效 发展 , 还要 符合 伦理 , 

In [14]:
import pandas as pd
import jieba
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans

df = pd.read_excel('新闻.xlsx')

# 分词
words = []
for i, row in df.iterrows():
    words.append(' '.join(jieba.cut(row['标题'])))

# TF-IDF 向量化
vect = TfidfVectorizer()
X = vect.fit_transform(words)

kms = KMeans(n_clusters=10, random_state=123)
labels = kms.fit_predict(X)

df['cluster'] = labels

for i in range(10):
    print(f"\n类别 {i}")
    print(df[df['cluster'] == i]['标题'].head(5).to_list())


类别 0
['体育场地共享 群众健身受惠', '江苏省体育局构建全民健身设施网络体系', '乐享全民健身公益体育彩票就在你我身边', '惠州将举行系列体育活动迎接全民健身日的到来', '惠州将举行系列体育活动迎接全民健身日的到来']

类别 1
['杨广伟:未来10年 人工智能一定会改变房地产行业', '文献述评:人工智能在精神科的应用', '严重提醒!骗子都用上AI技术了!你却还不知道啥是人工智能?', '“芯时代、芯征程、芯机遇”人工智能与机器视觉高峰论坛如期而至', '“读心术”新高地,基于血谱光学成像的情感人工智能']

类别 2
['华能国际:华能资本是华能贵诚信托有限公司大股东', '贵诚信托', '华能贵诚信托有限公司', '华能贵诚信托有限公司', '华能贵诚信托有限公司']

类别 3
['数字媒体的体育版权经营逻辑', '关心下一代华夏国际体育训练营丨美国体育训练营', '左手优酷体育右手苏宁体育 阿里体育组队围攻腾讯体育', '新赛季“抢人”大战正酣 优酷体育会员悄然下架', '学校体育资源开放,步子再快一点']

类别 4
['全球《财富》榜再次更新,阿里巴巴腾讯被反超?京东成最大黑马!', '腾讯、阿里巴巴、京东……等名字的由来,你知道哪些?', '格力全品类上线京东家电 与京东展开深度合作', '格力“联姻”京东 预计2年后进行业前四', '博鳌快讯 | 唐学斌:京东、360看中的是彩生活的社区服务模式']

类别 5
['信托公司2019年上半年经营业绩概览', '2018年信托业人均创利304万元 华润、华能贵诚跌出万亿俱乐部', '去年信托业人均创利304万元,华能贵诚信托跌出万亿俱乐部', '华能贵诚信托换帅,孙磊出任总经理', '持单家公司股票超产品净值20% 华能贵诚信托被罚20万元']

类别 6
['国金ABS云 · 早报丨招行与华能信托将合作发行99亿元ABS', '国金ABS云 · 早报丨招行与华能信托将合作发行99亿元ABS', '国金ABS云 · 早报丨招行与华能信托将合作发行99亿元ABS', '国金ABS云 · 早报丨招行与华能信托将合作发行99亿元ABS', '国金ABS云 · 早报丨招行与华能信托将合作发行99亿元ABS']

类别 7
['数据科学哪家强?Python和R的对决 - 博客园新闻手机版',

/opt/anaconda3/lib/python3.12/site-packages/sklearn/cluster/_kmeans.py:1416: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)


In [15]:
from sklearn.metrics.pairwise import cosine_similarity

# 计算余弦相似度
cos_sim = cosine_similarity(X)

# 打印前 5 条新闻的相似度矩阵
print("前5条新闻的余弦相似度：")
print(pd.DataFrame(cos_sim[:5, :5]))

similar_idx = cos_sim[0].argsort()[::-1][1:6]  # 降序，跳过自己
print("\n与第1条新闻最相似的5条：")
for idx in similar_idx:
    print(f"相似度={cos_sim[0, idx]:.3f} -> {df.loc[idx, '标题']}")

前5条新闻的余弦相似度：
     0         1         2         3         4
0  1.0  0.000000  0.000000  0.000000  0.000000
1  0.0  1.000000  0.063591  0.055208  0.055039
2  0.0  0.063591  1.000000  0.464255  0.084141
3  0.0  0.055208  0.464255  1.000000  0.073049
4  0.0  0.055039  0.084141  0.073049  1.000000

与第1条新闻最相似的5条：
相似度=0.292 -> 速睹62家信托上半年业绩!平安中信华能位列前三
相似度=0.215 -> 2018年上半年62家信托公司净利润排名 平安中信华能位列前三
相似度=0.210 -> 数字媒体的体育版权经营逻辑
相似度=0.138 -> 5.94亿重组遭问询 汇金科技否认标的公司卖资产粉饰业绩
相似度=0.121 -> 华能信托:信托公司参与消费金融的新机会与模式分析


In [16]:
from sklearn.cluster import DBSCAN

dbs = DBSCAN(eps=0.5, min_samples=5)
dbs.fit(X)
labels = dbs.labels_
df['cluster'] = labels
for i in range(10):
    print(f"\n类别 {i}")
    print(df[df['cluster'] == i]['标题'].head(5).to_list())



类别 0
['五矿信托首任总经理辞职 接任者或为华能信托王卓', '五矿信托首任总经理辞职 接任者或为华能信托王卓', '五矿信托首任总经理辞职 接任者或为华能信托王卓', '五矿信托首任总经理辞职 接任者或为华能信托王卓', '五矿信托首任总经理辞职 接任者或为华能信托王卓']

类别 1
['华夏幸福关于拟与华能信托签署《增资协议》的公告', '华夏幸福关于拟与华能信托签署《增资协议》的公告', '华夏幸福关于拟与华能信托签署《增资协议》的公告', '华夏幸福关于拟与华能信托签署《增资协议》的公告', '华夏幸福关于拟与华能信托签署《增资协议》的公告']

类别 2
['普邦股份:华能信托.普邦1号集合资金信托计划信托合同', '普邦股份:华能信托.普邦1号集合资金信托计划信托合同', '普邦股份:华能信托.普邦1号集合资金信托计划信托合同', '普邦股份:华能信托.普邦1号集合资金信托计划信托合同', '普邦股份:华能信托.普邦1号集合资金信托计划信托合同']

类别 3
['华能信托试水首单不良资产收益权转让已有46家信托公司与银登中心...', '华能信托试水首单不良资产收益权转让已有46家信托公司与银登中心...', '华能信托试水首单不良资产收益权转让已有46家信托公司与银登中心...', '华能信托试水首单不良资产收益权转让已有46家信托公司与银登中心...', '华能信托试水首单不良资产收益权转让已有46家信托公司与银登中心...']

类别 4
['北京银行携手华能、中航信托创新慈善信托模式', '北京银行携手华能、中航信托创新慈善信托模式', '北京银行携手华能、中航信托创新慈善信托模式', '北京银行携手华能、中航信托创新慈善信托模式', '北京银行携手华能、中航信托创新慈善信托模式']

类别 5
['ACCA-华能信托“财经领袖培养计划”第一期学员选拔结果公布', 'ACCA-华能信托“财经领袖培养计划”第一期学员选拔结果公布', 'ACCA-华能信托“财经领袖培养计划”第一期学员选拔结果公布', 'ACCA-华能信托“财经领袖培养计划”第一期学员选拔结果公布', 'ACCA-华能信托“财经领袖培养计划”第一期学员选拔结果公布']

类别 6
['华能贵诚信托有限公司', '华能贵诚信托有限公司', '华能贵诚信托有限公司', '华能贵

# 层次聚类

In [17]:
from sklearn.cluster import AgglomerativeClustering

# 如果 X 是稀疏矩阵（比如 TF-IDF 输出），需要转 dense
X_dense = X.toarray()

agg = AgglomerativeClustering(n_clusters=10, metric='cosine', linkage='average')
labels = agg.fit_predict(X_dense)

df['cluster'] = labels

for i in range(10):
    print(f"\n类别 {i}")
    print(df[df['cluster'] == i]['标题'].head(5).to_list())


类别 0
['华能信托:信托公司参与消费金融的新机会与模式分析', '文献述评:人工智能在精神科的应用', '严重提醒!骗子都用上AI技术了!你却还不知道啥是人工智能?', '“芯时代、芯征程、芯机遇”人工智能与机器视觉高峰论坛如期而至', '华为Atlas:AI遥感的“碧空慧眼”']

类别 1
['既要人工智能高效发展,还要符合伦理,该怎么做?', '又一项人工智能技术被确认,自动避开行人,开车睡觉或将成为现实', '欧洲联盟人工智能生态系统调查', '人工智能是一种受欢迎的推动力 可以为GDP增加数百万美元', '法律人工智能的十大前沿问题']

类别 2
['信托公司2019年上半年经营业绩概览', '助推人工智能创新资源聚集珠海', '湖南大力开展“科技成果转化年”活动', '看看韩雪住的豪宅,室内做了很多 “科技”设计,进门才知很实用', '活动汇丨成都8月科技互联网活动知多少?']

类别 3
['杨广伟:未来10年 人工智能一定会改变房地产行业', '渗透!人工智能将在10年内占领房地产市场?', '西媒盘点:2016年中国打响了人工智能发展的发令枪', '盘点全球各国人工智能战略:中国打响发令枪', '为什么全球的富豪主要集中在科技领域?']

类别 4
['亚马逊的StyleSnap是一款人工智能工具', '谷歌正在使用人工智能来预测风电场的输出功率', '谷歌正在使用人工智能来预测风电场的输出功率', '这类纪录片用“硬核影像”见证“硬核科技”', '三维传感组件公司“安思疆科技”获亿元A轮融资 北京清控金信资本...']

类别 5
['&gt; 科技局']

类别 6
['首单信托型企业ABS获批', '华能贵诚信托孙磊:金融科技助力打造开放信托生态', '华能贵诚信托孙磊:金融科技已经成为信托行业重要的基础设施', '格力电器股权转让意向方闭门开会 华能信托赫然在列', '直击格力电器意向投资者见面会:参会者华能信托背后现国务院国资委...']

类别 7
['Python3.7知其然知其所以然-第六章 字符串']

类别 8
['对话|山村女教师自制体育器材:听孩子说想当老师,我流泪了', '乖乖女不适合娱乐圈?她第一个不同意!', '娱乐圈里的真·糊咖混得有多惨?', '去年是分手季,今年是恋情季,娱乐圈的八月都组团吗', '娱乐记

# GMM

In [18]:
from sklearn.mixture import GaussianMixture

gmm = GaussianMixture(n_components=10, covariance_type='full')
gmm.fit(X_dense)
labels = gmm.predict(X_dense)
df['cluster'] = labels
for i in range(10):
    print(f"\n类别 {i}")
    print(df[df['cluster'] == i]['标题'].head(5).to_list())


类别 0
['杨广伟:未来10年 人工智能一定会改变房地产行业', '文献述评:人工智能在精神科的应用', '严重提醒!骗子都用上AI技术了!你却还不知道啥是人工智能?', '“芯时代、芯征程、芯机遇”人工智能与机器视觉高峰论坛如期而至', '“读心术”新高地,基于血谱光学成像的情感人工智能']

类别 1
['华能贵诚信托孙磊:金融科技已经成为信托行业重要的基础设施', '阿尔法蛋现身人工智能与教育大数据峰会,智能科技获点赞', '装病骗政府645万,科技远不是你想的那样', '昔日网游第一股迅游科技实控人被动减持,商誉压顶', 'ChinaJoy 2019丨ITheat热点科技展台人气火爆 这些精彩看点不容错过']

类别 2
['来腾讯音乐娱乐蔡徐坤全新EP派对探寻不一《YOUNG》的青春答案', 'TGC腾讯数字文创:腾讯的文化抱负', '腾讯云进入日本市场 今年目标是使国际营收增长至多5倍', '湖南省政府与腾讯公司签署深化合作框架协议', '腾讯(00700)需要喜茶']

类别 3
['华能贵诚信托孙磊:金融科技助力打造开放信托生态', '华能贵诚信托换帅,孙磊出任总经理', '华能国际:华能资本是华能贵诚信托有限公司大股东', '2018年上半年62家信托公司净利润排名 平安中信华能位列前三', '速睹62家信托上半年业绩!平安中信华能位列前三']

类别 4
['信托公司2019年上半年经营业绩概览', '首单信托型企业ABS获批', '格力电器股权转让意向方闭门开会 华能信托赫然在列', '直击格力电器意向投资者见面会:参会者华能信托背后现国务院国资委...', '格力电器股权转让意向投资者见面会召开 自称华能信托的人士到场']

类别 5
['数字媒体的体育版权经营逻辑', '关心下一代华夏国际体育训练营丨美国体育训练营', '左手优酷体育右手苏宁体育 阿里体育组队围攻腾讯体育', '新赛季“抢人”大战正酣 优酷体育会员悄然下架', '学校体育资源开放,步子再快一点']

类别 6
['国金ABS云 · 早报丨招行与华能信托将合作发行99亿元ABS', '国金ABS云 · 早报丨招行与华能信托将合作发行99亿元ABS', '国金ABS云 · 早报丨招行与华能信托将合作发行99亿元ABS', '国金ABS云 · 早报丨招行与华能信托将合作发行9

# HDBSCAN

In [19]:
from sklearn.cluster import HDBSCAN

hdbscan = HDBSCAN(min_cluster_size=5, min_samples=3)
hdbscan.fit(X_dense)
labels = hdbscan.labels_
df['cluster'] = labels
for i in range(10):
    print(f"\n类别 {i}")
    print(df[df['cluster'] == i]['标题'].head(5).to_list())


类别 0
['灵超尤长靖节目互动被无耻造谣?坤音娱乐老板惹众怒,竟贷款道歉', '尤长靖无辜躺枪?秦周懿言语中伤尤长靖,香蕉娱乐要求正式道歉', '坤音娱乐频出问题,自卜凡解约风波后,老板也因骂尤长靖而惹争议', '尤长靖无辜躺枪?秦周懿言语中伤尤长靖,香蕉娱乐要求正式道歉', '坤音娱乐频出问题,自卜凡解约风波后,老板也因骂尤长靖而惹争议']

类别 1
['乐队鼓手要失业?索尼用人工智能自动为音乐打节拍', '来腾讯音乐娱乐蔡徐坤全新EP派对探寻不一《YOUNG》的青春答案', '中国原声民歌节展现传统音乐非遗', '来腾讯音乐娱乐蔡徐坤全新EP派对探寻不一《YOUNG》的青春答案', '腾讯音乐“等风来”']

类别 2
['广州:中考体育跳绳满分标准逐步提高', '体育分值提至70分 “三大球”为选考项目', '体育分值提至70分 “三大球”为选考项目', '广州市中考体育部分加入足球、篮球、排球为选考项目', '「最新」沪学校体育艺术项目将形成小初高“一条龙”!这里有你关心...']

类别 3
['学好少儿编程,未来轻松掌控人工智能时代', '长春人工智能编程', '长春人工智能编程', '编程小少年有个人工智能大梦想', '编程小少年有个人工智能大梦想']

类别 4
['让夜间经济更有文化味 哪里才是真正“网红打卡地”?', '文化增活力 旅游添魅力 文旅融合讓濟南旅游悄然發生著變化', '讲好中国故事 展示文化魅力', '视频|临清首届汉服文化旅游周开幕 千年魅力文化尽在山水间', '「财经纵横」戴斌:旅游研究与文化建设,初心在哪里...']

类别 5
['一波三折的腾讯手游《拉结尔》最终定档3月底正式上线!', '腾讯独家代理手游《权力的游戏》首测,SLG游戏或打破手游布局!', '腾讯独家代理手游《权力的游戏》首测,SLG游戏或打破手游布局!', '腾讯完美强强联合《完美世界》手游,信仰测试定档1月16日', '那些为腾讯赚了上千亿的游戏人,都去哪了?']

类别 6
['中国又掌握一项核心科技:火箭残骸指哪儿落哪儿', 'Python虚拟环境详解', '腾讯拿它也没办法,详解为什么《剑网3:指尖江湖》不氪金', '腾讯等它内测等了35000多个小时,剑网3指尖江湖把时间花哪儿了?', '腾讯等它内测等了35000多个小时,剑网3指尖江湖把